### ISSUE TITLE
sincronizar

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-GRADOII-PL/proyecto-equipo-com#1]
Sincronizar el proyecto

**Comment by alu0100825893** [comment]
Ya esta sincronizado, aunque aun vamos a hacer mas cosas.

**Comment by alu0100886870** [comment]
El repositorio estaba en modo _PRIVATE_ (no sé por qué) pero ya lo he puesto público por si acaso.
Está todo sincronizado desde el día 6 de Junio (presentación de proyectos).
